config/routes.rb
TestApp::Application.routes.draw do
  resources :countries
  resources :titles
  resources :accounttypes
  resources :requeststatuses
  resources :requests
  resources :emoneyouts
  resources :applications
  resources :addresses
  resources :emoneyoutstandings
  resources :clearingouts
  resources :transactions
  resources :partyrelationships
  resources :accounts
  resources :parties
  resources :people

  get "pages/home"

  get "pages/controlpanel"

  resources :rights
  resources :useraccountrights
  resources :useraccounts
  
  match 'rightassignment', :to => 'useraccountrights#rightassignment'
  match 'rightassignment/assign', :to => 'useraccountrights#assign', :as => "right_assign"
  match 'rightassignment/revoke', :to => 'useraccountrights#revoke', :as => "right_revoke"
  
  match 'relationshipassignment', :to => 'partyrelationships#relationshipassignment'
  match 'relationshipassignment/assignpossession', :to => 'partyrelationships#assignpossession', :as => "assign_possession"
  match 'relationshipassignment/possessionrevoke', :to => 'partyrelationships#possessionrevoke', :as => "possession_revoke"
  
  match 'people/new', :to => 'people#new'    # because people#new is also called from a form_tag included in a view template
  
  root :to => "pages#controlpanel"
  

end

app/models/party.rb
class Party < ActiveRecord::Base
  has_one :person, :dependent => :destroy
  accepts_nested_attributes_for :person
  
  has_many :accounts, :dependent => :destroy
  accepts_nested_attributes_for :accounts
  
  has_many :addresses, :dependent => :destroy
  accepts_nested_attributes_for :addresses
  
  has_many :principal_possession_relationships, :class_name => "Partyrelationship", :foreign_key => :principal_id, :dependent => :destroy
  has_many :possessions, :through => :principal_possession_relationships, :source => :possession
  
  has_many :possession_principal_relationships, :class_name => "Partyrelationship", :foreign_key => :possession_id, :dependent => :destroy
  has_many :principals, :through => :possession_principal_relationships, :source => :principal

  validates :payment_iban, :presence => true
end



# == Schema Information
# Schema version: 20110306112019
#
# Table name: parties
#
#  id           :integer         not null, primary key
#  payment_iban :string(40)
#  created_at   :datetime
#  updated_at   :datetime
#

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, :with => :rescue_record_not_found
  
  # GET /parties
  # GET /parties.xml
  def index
    @parties = Party.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @parties }
    end
  end

  # GET /parties/1
  # GET /parties/1.xml
  def show
    @party = Party.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @party }
    end
  end

  # GET /parties/new
  # GET /parties/new.xml
  def new
    @party = Party.new
    if params[:request_id].nil?
      @party.build_person       # for has_one
      @party.accounts.build     # for has_many
      @party.addresses.build    # for has_many
    else
      request = Request.find(params[:request_id])
      # Account attributes
      @party.accounts.build(:accounttype_id => request.accounttype_id)
      # Person attributes
      @party.build_person(:title_id => request.title_id,
                          :degree => request.degree,
                          :first_name => request.first_name,
                          :middle_name => request.middle_name,
                          :last_name => request.last_name,
                          :email => request.email,
                          :telephone => request.telephone,
                          :birth_date => request.birth_date,
                          :birth_place => request.birth_place )
      # Party attributes
      @party.payment_iban = request.payment_iban
      # Address attributes
      @party.addresses.build(:street => request.street,
                             :housenumber => request.housenumber,
                             :postal_supplement => request.postal_supplement,
                             :zipcode => request.zipcode,
                             :city => request.city,
                             :country_id => request.country_id )
    end  
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @party }
    end
  end

  # GET /parties/1/edit
  def edit
    @party = Party.find(params[:id])
  end

  # POST /parties
  # POST /parties.xml
  def create
    @party = Party.new(params[:party])

    respond_to do |format|
      if @party.save
        flash[:success] = "Party was successfully created."
        format.html { redirect_to(@party) }
        format.xml  { render :xml => @party, :status => :created, :location => @party }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @party.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /parties/1
  # PUT /parties/1.xml
  def update
    @party = Party.find(params[:id])

    respond_to do |format|
      if @party.update_attributes(params[:party])
        flash[:success] = "Party was successfully updated."
        format.html { redirect_to(@party) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @party.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /parties/1
  # DELETE /parties/1.xml
  def destroy
    @party = Party.find(params[:id])
    @party.destroy

    respond_to do |format|
      format.html { redirect_to(parties_url) }
      format.xml  { head :ok }
    end
  end
  
protected
  # Rescue if record not found
  def rescue_record_not_found
    flash[:notice] = "No such entry found."
    redirect_to new_party_path
  end
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/views/parties/_form.html.erb
<%= form_for(@party) do |f| %>
  <%= render "shared/error_messages", :target => @party %>

  <hr />
  <!-- Account attributes -->
  <%= f.fields_for :accounts do |acc| %>
    <div class="field">
      <%= acc.label :accounttype_id, "Account type" %><%= mark_required(@party.accounts.first, :accounttype_id) %><br />
      <%= acc.collection_select(:accounttype_id, Accounttype.all, :id, :description, {:prompt => true} ) %>
    </div>
  <% end %>
  
   <!-- Person attributes -->  
  <%= f.fields_for :person do |p| %>
    <div class="field">
      <%= p.label :title_id %><%= mark_required(@party.person, :title_id) %><br />
      <%= p.collection_select(:title_id, Title.all, :id, :description, {:prompt => true} ) %>
    </div>
     <div class="field">
      <%= p.label :degree %><%= mark_required(@party.person, :degree) %><br />
      <%= p.text_field :degree %>
    </div>
    <div class="field">
      <%= p.label :first_name, "First name" %><%= mark_required(@party.person, :first_name) %><br />
      <%= p.text_field :first_name %>
    </div>
    <div class="field">
      <%= p.label :middle_name, "Middle name" %><%= mark_required(@party.person, :middle_name) %><br />
      <%= p.text_field :middle_name %>
    </div>
    <div class="field">
      <%= p.label :last_name, "Last name" %><%= mark_required(@party.person, :last_name) %><br />
      <%= p.text_field :last_name %>
    </div>
    
    <!-- Party attributes -->
    <div class="field">
      <%= f.label :payment_iban, "Payment account (IBAN)" %><%= mark_required(@party, :payment_iban) %><br />
      <%= f.text_field :payment_iban %>
    </div>
    
    <!-- Person attributes proceeding-->
    <div class="field">
      <%= p.label :email %><%= mark_required(@party.person, :email) %><br />
      <%= p.text_field :email %>
    </div>
    <div class="field">
      <%= p.label :telephone %><%= mark_required(@party.person, :telephone) %><br />
      <%= p.text_field :telephone %>
    </div>
    <div class="field">
      <%= p.label :birth_date %><%= mark_required(@party.person, :birth_date) %><br />
      <%= p.date_select(:birth_date, :start_year => 1940, :end_year => Date.current.year) %>
    </div>
    <div class="field">
      <%= p.label :birth_place %><%= mark_required(@party.person, :birth_place) %><br />
      <%= p.text_field :birth_place %>
    </div>
  <% end %>
  
  <!-- Address attributes -->
  <%= f.fields_for :addresses do |build| %>
    <div class="field">
      <%= build.label :street %><%= mark_required(@party.addresses.first, :street) %><br />
      <%= build.text_field :street %>
    </div>
    <div class="field">
      <%= build.label :housenumber, "House number" %><%= mark_required(@party.addresses.first, :housenumber) %><br />
      <%= build.text_field :housenumber %>
    </div>
    <div class="field">
      <%= build.label :postal_supplement %><%= mark_required(@party.addresses.first, :postal_supplement) %><br />
      <%= build.text_field :postal_supplement %>
    </div>
    <div class="field">
      <%= build.label :zipcode %><%= mark_required(@party.addresses.first, :zipcode) %><br />
      <%= build.text_field :zipcode %>
    </div>
    <div class="field">
      <%= build.label :city %><%= mark_required(@party.addresses.first, :city) %><br />
      <%= build.text_field :city %>
    </div>
    <div class="field">
      <%= build.label :country_id %><%= mark_required(@party.addresses.first, :country_id) %><br />
      <%= build.collection_select(:country_id, Country.all(:order => 'description'), :id, :description, {:prompt => true} ) %>
    </div>
  <% end %>

  <hr />
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/parties/edit.html.erb
<h1>Editing party</h1>

<%= render 'form' %>

<%= link_to 'Show', @party %> |
<%= link_to 'Back', parties_path %>

app/views/parties/index.html.erb
<h1>Listing parties</h1>

<table>
  <tr>
    <th>Party ID</th>
    <th>Payment IBAN</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @parties.each do |party| %>
  <tr>
    <td><%= party.id %></td>
    <td><%= party.payment_iban %></td>
    <td><%= link_to 'Show', party %></td>
    <td><%= link_to 'Edit', edit_party_path(party) %></td>
    <td><%= link_to 'Destroy', party, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Party', new_party_path %>

app/views/parties/new.html.erb
<h1>New party</h1>
<!-- Query form to get requests (applications) -->
<hr />
<% form_tag :new_party, :method => :get do %>
  <%= label_tag 'request_id', 'Request ID' %><br />
  <%= text_field_tag :request_id, params[:request_id] %>
  <%= submit_tag "Get request", :name => nil %>
<% end %>

<%= render 'form' %>

<%= link_to 'Back', parties_path %>

app/views/parties/show.html.erb
<table>
  <tr>
    <td width=200px>Party ID</td>
    <td><%= @party.id %></td>
  </tr>
  <tr>
    <td>E-money accounts</td>
    <td>
      <% if @party.accounts.any? %>
        <% @party.accounts.each do |acc| %>
          - <%= link_to acc.account_number, account_path(:id => acc.id) %> -
        <% end %>
      <% end %>
    </td> 
  </tr>
  <tr>
    <td>User account</td>
    <% @person_id = @party.person.id %>
    <td><%= create_useraccount_on_fail {link_to(@party.person.useraccount.username, @party.person.useraccount) } %></td>
  </tr>
  <tr>
    <td>Title ID</td>
    <td><%= none_on_fail {@party.person.title.description} %></td>
  </tr>
  <tr>
    <td>Degree</td>
    <td><%= @party.person.degree %></td>
  </tr>
  <tr>
    <td>First name</td>
    <td><%= @party.person.first_name %></td>
  </tr>
  <tr>
    <td>Middle name</td>
    <td><%= @party.person.middle_name %></td>
  </tr>
  <tr>
    <td>Last name</td>
    <td><%= @party.person.last_name %></td>
  </tr>
  <tr>
    <td>Payment account (IBAN)</td>
    <td><%= @party.payment_iban %></td>
  </tr>
  <tr>
    <td>Email</td>
    <td><%= @party.person.email %></td>
  </tr>
  <tr>
    <td>Telephone</td>
    <td><%= @party.person.telephone %></td>
  </tr>
  <tr>
    <td>Birth date</td>
    <td><%= @party.person.birth_date %></td>
  </tr>
  <tr>
    <td>Birth place</td>
    <td><%= @party.person.birth_place %></td>
  </tr>
  <tr>
    <td>Addresses</td>
    <td>
      <% if @party.addresses.any? %>
        <% @party.addresses.each do |add| %>
          <%  comp = add.street + " " + add.housenumber + ", " + add.zipcode + " " + add.city %>
          - <%= link_to(comp, address_path(:id => add.id)) %> -
        <% end %>
      <% end %>
    </td>
  </tr>
</table>

<%= link_to 'Edit', edit_party_path(@party) %> |
<%= link_to 'Back', parties_path %>