config/routes.rb
TestApp::Application.routes.draw do
  resources :countries
  resources :titles
  resources :accounttypes
  resources :requeststatuses
  resources :requests
  resources :emoneyouts
  resources :applications
  resources :addresses
  resources :emoneyoutstandings
  resources :clearingouts
  resources :transactions
  resources :partyrelationships
  resources :accounts
  resources :parties
  resources :people

  get "pages/home"

  get "pages/controlpanel"

  resources :rights
  resources :useraccountrights
  resources :useraccounts
  
  match 'rightassignment', :to => 'useraccountrights#rightassignment'
  match 'rightassignment/assign', :to => 'useraccountrights#assign', :as => "right_assign"
  match 'rightassignment/revoke', :to => 'useraccountrights#revoke', :as => "right_revoke"
  
  match 'relationshipassignment', :to => 'partyrelationships#relationshipassignment'
  match 'relationshipassignment/assignpossession', :to => 'partyrelationships#assignpossession', :as => "assign_possession"
  match 'relationshipassignment/possessionrevoke', :to => 'partyrelationships#possessionrevoke', :as => "possession_revoke"
  
  match 'people/new', :to => 'people#new'    # because people#new is also called from a form_tag included in a view template
  
  root :to => "pages#controlpanel"
  

end

app/models/emoneyoutstanding.rb
class Emoneyoutstanding < ActiveRecord::Base
  # calculates total amount of e-money in circulation and build history in DB
  def self.history_emoney_outstanding
    calc_daily_credit_debit
    prior_date = Date.current - 1
    unless Emoneyoutstanding.find_by_date(prior_date).nil?
      prior_date_amount = Emoneyoutstanding.find_by_date(prior_date).amount
    else
      prior_date_amount = 0
      Log.warn("No prior date amount for e-money in circulation has been found. The prior date amount has been set to zero. This may be all right for first initiation.")
    end
    $overalltotal = prior_date_amount + @dailytotal
    Emoneyoutstanding.create(:amount => $overalltotal, :date => Date.current)
    return $overalltotal
  end
end

private
  # calculate daily total for e-money issued and re-changed
  def calc_daily_credit_debit
   credit = Transaction.sum(:amount, :conditions => "date IS '#{Date.current}' AND sign IS 'c' ")
   debit = Transaction.sum(:amount, :conditions => "date IS '#{Date.current}' AND sign IS 'd' ")
   @dailytotal = credit - debit
   return @dailytotal
  end
  
# == Schema Information
# Schema version: 20110221082811
#
# Table name: emoneyoutstandings
#
#  id         :integer         not null, primary key
#  amount     :decimal(, )
#  date       :date
#  created_at :datetime
#  updated_at :datetime
#

app/controllers/emoneyoutstandings_controller.rb
class EmoneyoutstandingsController < ApplicationController
  # GET /emoneyoutstandings
  # GET /emoneyoutstandings.xml
  def index
    @emoneyoutstandings = Emoneyoutstanding.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @emoneyoutstandings }
    end
  end

  # GET /emoneyoutstandings/1
  # GET /emoneyoutstandings/1.xml
  def show
    @emoneyoutstanding = Emoneyoutstanding.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @emoneyoutstanding }
    end
  end

  # GET /emoneyoutstandings/new
  # GET /emoneyoutstandings/new.xml
  def new
    @emoneyoutstanding = Emoneyoutstanding.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @emoneyoutstanding }
    end
  end

  # GET /emoneyoutstandings/1/edit
  def edit
    @emoneyoutstanding = Emoneyoutstanding.find(params[:id])
  end

  # POST /emoneyoutstandings
  # POST /emoneyoutstandings.xml
  def create
    @emoneyoutstanding = Emoneyoutstanding.new(params[:emoneyoutstanding])

    respond_to do |format|
      if @emoneyoutstanding.save
        format.html { redirect_to(@emoneyoutstanding, :notice => 'Emoneyoutstanding was successfully created.') }
        format.xml  { render :xml => @emoneyoutstanding, :status => :created, :location => @emoneyoutstanding }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @emoneyoutstanding.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /emoneyoutstandings/1
  # PUT /emoneyoutstandings/1.xml
  def update
    @emoneyoutstanding = Emoneyoutstanding.find(params[:id])

    respond_to do |format|
      if @emoneyoutstanding.update_attributes(params[:emoneyoutstanding])
        format.html { redirect_to(@emoneyoutstanding, :notice => 'Emoneyoutstanding was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @emoneyoutstanding.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /emoneyoutstandings/1
  # DELETE /emoneyoutstandings/1.xml
  def destroy
    @emoneyoutstanding = Emoneyoutstanding.find(params[:id])
    @emoneyoutstanding.destroy

    respond_to do |format|
      format.html { redirect_to(emoneyoutstandings_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/emoneyoutstandings_helper.rb
module EmoneyoutstandingsHelper
end

app/views/emoneyoutstandings/_form.html.erb
<%= form_for(@emoneyoutstanding) do |f| %>
  <% if @emoneyoutstanding.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@emoneyoutstanding.errors.count, "error") %> prohibited this emoneyoutstanding from being saved:</h2>

      <ul>
      <% @emoneyoutstanding.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/emoneyoutstandings/edit.html.erb
<h1>Editing emoneyoutstanding</h1>

<%= render 'form' %>

<%= link_to 'Show', @emoneyoutstanding %> |
<%= link_to 'Back', emoneyoutstandings_path %>

app/views/emoneyoutstandings/index.html.erb
<h1>Listing emoneyoutstandings</h1>

<table>
  <tr>
    <th>Amount</th>
    <th>Date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @emoneyoutstandings.each do |emoneyoutstanding| %>
  <tr>
    <td><%= emoneyoutstanding.amount %></td>
    <td><%= emoneyoutstanding.date %></td>
    <td><%= link_to 'Show', emoneyoutstanding %></td>
    <td><%= link_to 'Edit', edit_emoneyoutstanding_path(emoneyoutstanding) %></td>
    <td><%= link_to 'Destroy', emoneyoutstanding, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Emoneyoutstanding', new_emoneyoutstanding_path %>

app/views/emoneyoutstandings/new.html.erb
<h1>New emoneyoutstanding</h1>

<%= render 'form' %>

<%= link_to 'Back', emoneyoutstandings_path %>

app/views/emoneyoutstandings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Amount:</b>
  <%= @emoneyoutstanding.amount %>
</p>

<p>
  <b>Date:</b>
  <%= @emoneyoutstanding.date %>
</p>


<%= link_to 'Edit', edit_emoneyoutstanding_path(@emoneyoutstanding) %> |
<%= link_to 'Back', emoneyoutstandings_path %>