config/routes.rb
TestApp::Application.routes.draw do
  resources :countries
  resources :titles
  resources :accounttypes
  resources :requeststatuses
  resources :requests
  resources :emoneyouts
  resources :applications
  resources :addresses
  resources :emoneyoutstandings
  resources :clearingouts
  resources :transactions
  resources :partyrelationships
  resources :accounts
  resources :parties
  resources :people

  get "pages/home"

  get "pages/controlpanel"

  resources :rights
  resources :useraccountrights
  resources :useraccounts
  
  match 'rightassignment', :to => 'useraccountrights#rightassignment'
  match 'rightassignment/assign', :to => 'useraccountrights#assign', :as => "right_assign"
  match 'rightassignment/revoke', :to => 'useraccountrights#revoke', :as => "right_revoke"
  
  match 'relationshipassignment', :to => 'partyrelationships#relationshipassignment'
  match 'relationshipassignment/assignpossession', :to => 'partyrelationships#assignpossession', :as => "assign_possession"
  match 'relationshipassignment/possessionrevoke', :to => 'partyrelationships#possessionrevoke', :as => "possession_revoke"
  
  match 'people/new', :to => 'people#new'    # because people#new is also called from a form_tag included in a view template
  
  root :to => "pages#controlpanel"
  

end

app/models/useraccountright.rb
class Useraccountright < ActiveRecord::Base
  belongs_to :useraccount, :touch => true
  belongs_to :right
end

# == Schema Information
# Schema version: 20110211100713
#
# Table name: useraccountrights
#
#  id             :integer         not null, primary key
#  useraccount_id :integer
#  right_id       :integer
#  created_at     :datetime
#  updated_at     :datetime
#

app/controllers/useraccountrights_controller.rb
class UseraccountrightsController < ApplicationController
  # view and manage useraccount right assignments
  def rightassignment
    @rights = Right.all
    unless params[:username].nil?
      @useraccount = Useraccount.find_by_username(params[:username])
      $username = params[:username]
    end
    
    if @useraccount.nil?
      flash.now[:notice] = "No useraccount found."
    end
    
    respond_to do |format|
      format.html # rightassignment.html.erb
      format.xml  { render :xml => @useraccountrights }
    end
  end
  
  # assign rights to useraccounts
  def assign
    useraccount = Useraccount.find_by_username(params[:username])
    right = Right.find(params[:right_id])
    useraccount.rights << right
    
    redirect_to :action => 'rightassignment', :username => params[:username]
  end
  
  # revoke rights from useraccounts
  def revoke
    useraccount = Useraccount.find_by_username(params[:username])
    right = Right.find(params[:right_id])
    useraccount.rights.delete(right)
    useraccount.touch                           # sets useraccount.updated_at to now
    
    redirect_to :action => 'rightassignment', :username => params[:username]
  end
  
  # GET /useraccountrights
  # GET /useraccountrights.xml
  def index
    @useraccountrights = Useraccountright.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @useraccountrights }
    end
  end

  # GET /useraccountrights/1
  # GET /useraccountrights/1.xml
  def show
    @useraccountright = Useraccountright.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @useraccountright }
    end
  end

  # GET /useraccountrights/new
  # GET /useraccountrights/new.xml
  def new
    @useraccountright = Useraccountright.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @useraccountright }
    end
  end

  # GET /useraccountrights/1/edit
  def edit
    @useraccountright = Useraccountright.find(params[:id])
  end

  # POST /useraccountrights
  # POST /useraccountrights.xml
  def create
    @useraccountright = Useraccountright.new(params[:useraccountright])

    respond_to do |format|
      if @useraccountright.save
        format.html { redirect_to(@useraccountright, :notice => 'Useraccountright was successfully created.') }
        format.xml  { render :xml => @useraccountright, :status => :created, :location => @useraccountright }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @useraccountright.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /useraccountrights/1
  # PUT /useraccountrights/1.xml
  def update
    @useraccountright = Useraccountright.find(params[:id])

    respond_to do |format|
      if @useraccountright.update_attributes(params[:useraccountright])
        format.html { redirect_to(@useraccountright, :notice => 'Useraccountright was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @useraccountright.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /useraccountrights/1
  # DELETE /useraccountrights/1.xml
  def destroy
    @useraccountright = Useraccountright.find(params[:id])
    @useraccountright.destroy

    respond_to do |format|
      format.html { redirect_to(useraccountrights_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/useraccountrights_helper.rb
module UseraccountrightsHelper
end

app/views/useraccountrights/_form.html.erb
<%= form_for(@useraccountright) do |f| %>
  <% if @useraccountright.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@useraccountright.errors.count, "error") %> prohibited this useraccountright from being saved:</h2>

      <ul>
      <% @useraccountright.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :useraccount_id %><br />
    <%= f.text_field :useraccount_id %>
  </div>
  <div class="field">
    <%= f.label :right_id %><br />
    <%= f.text_field :right_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/useraccountrights/edit.html.erb
<h1>Editing useraccountright</h1>

<%= render 'form' %>

<%= link_to 'Show', @useraccountright %> |
<%= link_to 'Back', useraccountrights_path %>

app/views/useraccountrights/index.html.erb
<h1>Listing useraccountrights</h1>

<table>
  <tr>
    <th>Useraccount</th>
    <th>Right</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @useraccountrights.each do |useraccountright| %>
  <tr>
    <td><%= useraccountright.useraccount_id %></td>
    <td><%= useraccountright.right_id %></td>
    <td><%= link_to 'Show', useraccountright %></td>
    <td><%= link_to 'Edit', edit_useraccountright_path(useraccountright) %></td>
    <td><%= link_to 'Destroy', useraccountright, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Useraccountright', new_useraccountright_path %>

app/views/useraccountrights/new.html.erb
<h1>New useraccountright</h1>

<%= render 'form' %>

<%= link_to 'Back', useraccountrights_path %>

app/views/useraccountrights/rightassignment.html.erb
<h1>Useraccount right assignment</h1>

<% form_tag :controller => "useraccountrights", :action => "rightassignment", :method => :get do %>
  <%= label_tag 'username', 'Username' %><br />
  <%= text_field_tag :username, params[:username] %>
  <%= submit_tag "Submit", :name => nil %>
<% end %>

<% unless @useraccount.nil? %>
  <table>
    <tr>
      <th>Description</th>
    </tr>

    <% @rights.each do |right| %>  
      <tr>  
        <td><%= right.description %></td>    
        <% if @useraccount.rights.exists?(right.id) %>
          <td>[X] <%= link_to 'revoke', right_revoke_path(:right_id => right, :username => $username) %></td>
        <% else %>
          <td>[_] <%= link_to 'assign', right_assign_path(:right_id => right, :username => $username) %></td>
        <% end %>
      </tr>  
    <% end %>
  </table>
<% end %>
<br />
<%= link_to 'Controlpanel', root_path %>

app/views/useraccountrights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Useraccount:</b>
  <%= @useraccountright.useraccount_id %>
</p>

<p>
  <b>Right:</b>
  <%= @useraccountright.right_id %>
</p>


<%= link_to 'Edit', edit_useraccountright_path(@useraccountright) %> |
<%= link_to 'Back', useraccountrights_path %>